### ISSUE TITLE
exiting before measureing all qubits generates many unfriendly error messages

### ISSUE THREAD

**Issue by silky** [ProjectQ-Framework/ProjectQ#2]
to reproduce, modify the `quantum_random_numbers.py` to have

`raise Exception("...")` just above the `Measure | q1` operation

i get the following

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/noon/dev/ProjectQ/projectq/cengines/_main.py", line 133, in <lambda>
    self._delfun = lambda x: x.flush(deallocate_qubits=True)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_main.py", line 227, in flush
    qb.__del__()
  File "/home/noon/dev/ProjectQ/projectq/types/_qubit.py", line 114, in __del__
    self.engine.deallocate_qubit(self)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 151, in deallocate_qubit
    self.send([Command(self, Deallocate, ([qubit],))])
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
    self.next_engine.receive(command_list)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_tagremover.py", line 56, in receive
    self.send([cmd])
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
    self.next_engine.receive(command_list)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 236, in receive
    self._cache_cmd(cmd)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 222, in _cache_cmd
    self._check_and_send()
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 200, in _check_and_send
    self._send_qubit_pipeline(i, len(self._l[i]))
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 78, in _send_qubit_pipeline
    self.send([il[i]])
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
    self.next_engine.receive(command_list)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_replacer/_replacer.py", line 188, in receive
    self._process_command(cmd)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_replacer/_replacer.py", line 124, in _process_command
    self.send([cmd])
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
    self.next_engine.receive(command_list)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_tagremover.py", line 56, in receive
    self.send([cmd])
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
    self.next_engine.receive(command_list)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 236, in receive
    self._cache_cmd(cmd)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 222, in _cache_cmd
    self._check_and_send()
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 200, in _check_and_send
    self._send_qubit_pipeline(i, len(self._l[i]))
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 78, in _send_qubit_pipeline
    self.send([il[i]])
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
    self.next_engine.receive(command_list)
  File "/home/noon/dev/ProjectQ/projectq/backends/_sim/_simulator.py", line 181, in receive
    self._handle(cmd)
  File "/home/noon/dev/ProjectQ/projectq/backends/_sim/_simulator.py", line 147, in _handle
    self._simulator.deallocate_qubit(ID)
RuntimeError: Error: Qubit has not been measured / uncomputed! There is most likely a bug in your code.
Exception ignored in: <bound method Qubit.__del__ of <projectq.types._qubit.Qubit object at 0x7fcce59c5f60>>
Traceback (most recent call last):
  File "/home/noon/dev/ProjectQ/projectq/types/_qubit.py", line 114, in __del__
    self.engine.deallocate_qubit(self)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 151, in deallocate_qubit
    self.send([Command(self, Deallocate, ([qubit],))])
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
    self.next_engine.receive(command_list)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_tagremover.py", line 56, in receive
    self.send([cmd])
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
    self.next_engine.receive(command_list)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 236, in receive
    self._cache_cmd(cmd)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 222, in _cache_cmd
    self._check_and_send()
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 194, in _check_and_send
    self._optimize(i)
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 136, in _optimize
    inv = self._l[idx][i].get_inverse()
  File "/home/noon/dev/ProjectQ/projectq/ops/_command.py", line 133, in get_inverse
    cmd = Command(self._engine, projectq.ops.get_inverse(self.gate), self.qubits)
  File "/home/noon/dev/ProjectQ/projectq/ops/_metagates.py", line 117, in get_inverse
    return gate.get_inverse()
  File "/home/noon/dev/ProjectQ/projectq/ops/_basics.py", line 215, in get_inverse
    return deepcopy(self)
  File "/home/noon/tools/anaconda3/envs/projectq/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
AttributeError: 'NoneType' object has no attribute '__newobj__'
Exception ignored in: <bound method MainEngine.__del__ of <projectq.cengines._main.MainEngine object at 0x7fccfded00f0>>
Traceback (most recent call last):
  File "/home/noon/dev/ProjectQ/projectq/cengines/_main.py", line 143, in __del__
  File "/home/noon/dev/ProjectQ/projectq/cengines/_main.py", line 229, in flush
  File "/home/noon/dev/ProjectQ/projectq/cengines/_main.py", line 214, in receive
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
  File "/home/noon/dev/ProjectQ/projectq/cengines/_tagremover.py", line 56, in receive
  File "/home/noon/dev/ProjectQ/projectq/cengines/_basics.py", line 191, in send
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 232, in receive
  File "/home/noon/dev/ProjectQ/projectq/cengines/_optimize.py", line 136, in _optimize
  File "/home/noon/dev/ProjectQ/projectq/ops/_command.py", line 133, in get_inverse
  File "/home/noon/dev/ProjectQ/projectq/ops/_metagates.py", line 117, in get_inverse
  File "/home/noon/dev/ProjectQ/projectq/ops/_basics.py", line 215, in get_inverse
  File "/home/noon/tools/anaconda3/envs/projectq/lib/python3.5/copy.py", line 174, in deepcopy
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
```

i don't think this is good. i'm guessing the cleanup code just needs a bit of a clean up :)

**Comment by thomashaener** [comment]
Hi! This is actually a feature of the simulator: All qubits must either be measured or uncomputed before they can be deallocated; otherwise an exception is raised (above it says "RuntimeError: Error: Qubit has not been measured / uncomputed! There is most likely a bug in your code.").
The last few errors are due to the Python garbage collection: When Python is exiting, it assigns None to all variables, including, e.g., imported modules such as copy. This leads to errors such as "TypeError: 'NoneType' object is not iterable".
If you delay the final clean-up by putting the code into a function and catching your Exception("...") in the main program, only see the exception thrown by the simulator would show up (namely as an ignored exception which occurred when dealing with your Exception("...")).

**Comment by silky** [comment]
i think it's a mistake to consider this a feature; it makes programming with this framework not particularly enjoyable.

i agree that it is good to do some cleanup of resources when the application exits, but the resource clean-up should be very robust.

imagine if the same thing happened when you exited a database-reading application before closing all connections - that code doesn't emit a new exception per connection you had open, informing you that you should've closed it.

**Comment by damiansteiger** [comment]
Programming in this framework is particularly nice as it supports automatic management of qubits (no need to explicitly deallocate qubits).

Any back-end can expect the following:
It receives an allocate qubit command for each qubit you allocate in your quantum program and also receives a deallocate qubit (at the latest when your program finishes). This is implemented using atexit...

Different back-ends can have their own implementation of what happens when a qubit is deallocated.

The simulator for example checks that your qubit is either measured or in a computational basis state (otherwise an exception is thrown as you have seen above). For example, if your program contains ` with Compute(eng)` and `with CustomUncompute(eng)` statements, it will check that you implemented them correctly. (I also like the -Wpedantic flag when programming in C++ :)

The main purpose of a quantum simulator is to test and debug quantum programs and hence we think this is an actual feature.

A hardware back-end will not throw you such an error (as it cannot figure out that you made a mistake) but just return the wrong result...
