### ISSUE TITLE
IBM backend not working

### ISSUE THREAD

**Issue by nicolocandiani** [ProjectQ-Framework/ProjectQ#296]
Hi,
I tried copying the code in this example: [https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/examples/ibm.py](https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/examples/ibm.py)

```
import projectq.setups.ibm
from projectq.backends import IBMBackend
from projectq.ops import Measure, Entangle, All
from projectq import MainEngine


def run_entangle(eng, num_qubits=5):
    """
        Runs an entangling operation on the provided compiler engine.
        Args:
        eng (MainEngine): Main compiler engine to use.
        num_qubits (int): Number of qubits to entangle.
        Returns:
        measurement (list<int>): List of measurement outcomes.
        """
    # allocate the quantum register to entangle
    qureg = eng.allocate_qureg(num_qubits)
    
    # entangle the qureg
    Entangle | qureg
    
    # measure; should be all-0 or all-1
    All(Measure) | qureg
    
    # run the circuit
    eng.flush()
    
    # access the probabilities via the back-end:
    results = eng.backend.get_probabilities(qureg)
    for state in results:
        print("Measured {} with p = {}.".format(state, results[state]))
    
    # return one (random) measurement outcome.
    return [int(q) for q in qureg]


if __name__ == "__main__":
    # create main compiler engine for the IBM back-end
    eng = MainEngine(IBMBackend(use_hardware=True, num_runs=1024,
                                verbose=False, device='ibmqx4'),
                     engine_list=projectq.setups.ibm.get_engine_list())
                     # run the circuit and print the result
    print(run_entangle(eng))
```

The code compiles and I successfully log in to the server. It says waiting for results and I get the job id, but soon after this I get a Traceback and it crashes.

```
Currently there are 94 jobs queued for execution on ibmqx4.
Traceback (most recent call last):
  File "ibmBackend.py", line 43, in <module>
    print(run_entangle(eng))
  File "ibmBackend.py", line 26, in run_entangle
    eng.flush()
  File "/usr/local/lib/python2.7/site-packages/projectq/cengines/_main.py", line 304, in flush
    self.receive([Command(self, FlushGate(), ([WeakQubitRef(self, -1)],))])
  File "/usr/local/lib/python2.7/site-packages/projectq/cengines/_main.py", line 266, in receive
    self.send(command_list)
  File "/usr/local/lib/python2.7/site-packages/projectq/cengines/_main.py", line 288, in send
    raise compact_exception  # use verbose=True for more info
Exception: Failed to run the circuit. Aborting.
 raised in:
'  File "/usr/local/lib/python2.7/site-packages/projectq/backends/_ibm/_ibm.py", line 295, in _run'
'    raise Exception("Failed to run the circuit. Aborting.")'
```

I'm using macOS 10.14.2 and I installed projectq on my machine using pip.

**Comment by nicolocandiani** [comment]
I found the error. When creating the compiler engine, if the use_hardware option is set on True the code crashes as soon as it's executed on the ibmqx4. If it is set to true it works. I already edited the example and made a pull request to fix the bug
