### ISSUE TITLE
Unable to install projectq using pip

### ISSUE THREAD

**Issue by juraskumar** [ProjectQ-Framework/ProjectQ#335]
Hi. I have been trying to install projectq on Windows using pip install. when using the command: `pip install projectq` I get the following error.
`
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\pc\AppData\Local\Temp\pip-install-jiybociz\projectq\setup.py", line 171, in <module>
        packages=find_packages()
      File "c:\users\pc\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\pc\anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\pc\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\pc\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install.py", line 61, in run
      File "c:\users\pc\anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\pc\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\pc\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\pc\anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\pc\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\pc\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\pc\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\build_ext.py", line 77, in run
      File "c:\users\pc\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 185, in run
        _build_ext.build_ext.run(self)
      File "c:\users\pc\anaconda3\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\pc\AppData\Local\Temp\pip-install-jiybociz\projectq\setup.py", line 109, in build_extensions
        self.warning("Something is wrong with your C++ compiler.\n"
      File "C:\Users\pc\AppData\Local\Temp\pip-install-jiybociz\projectq\setup.py", line 151, in warning
        raise Exception(warning_text + "\nCould not install the C++-Simulator."
    Exception: Something is wrong with your C++ compiler.
    Failed to compile a simple test program!

    Could not install the C++-Simulator.
    ProjectQ will default to the (slow) Python simulator.
    Use --without-cppsimulator to skip building the (faster) C++ version of the simulator.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\pc\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pc\\AppData\\Local\\Temp\\pip-install-jiybociz\\projectq\\setup.py'"'"'; __file__='"'"'C:\\Users\\pc\\AppData\\Local\\Temp\\pip-install-jiybociz\\projectq\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pc\AppData\Local\Temp\pip-record-mkr2dw6a\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
`

**Comment by juraskumar** [comment]
I have also tried installing without the simulator using 
`(C:\Users\pc\Anaconda3) C:\Users\pc>python -m pip install --user --global-option=--without-cppsimulator .


C:\Users\pc\Anaconda3\lib\site-packages\pip\_internal\commands\install.py:243: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`

**Comment by Takishima** [comment]
To install without the C++ simulator, you should not include a period at the end of your `pip` command:

```bash
python -m pip install --user --global-option=--without-cppsimulator projectq
```

**Comment by Takishima** [comment]
According to the error message above, the installation process cannot find a working C++ compiler. Do you have Visual Studio or the Visual Studio Build Tools installed on your computer?

**Comment by juraskumar** [comment]
Hi thanks for the comment about the period. After trying that out, I have installed projectq without the simulator. However i wish to still get the simulator version. I have installed Visual Studio Build Tools 2019 on my computer (version 16.2.4). So i am not sure why I cant get the faster version of projectq installed. Should i do something more than installing Build Tools?

**Comment by juraskumar** [comment]
Update: When i use the command `pip list`, I get projectq 0.4.2 in the list. However when I try importing project q in Spyder, i get the ModuleNotFoundError: no module named 'projectq'. Any help would be much appreciated.

**Comment by Takishima** [comment]
You probably need to have the Windows SDK installed as well.

**Comment by Takishima** [comment]
Were you able to solve your problem? If not, what is holding you at the moment?

**Comment by Takishima** [comment]
I'll be closing the issue since it is inactive. Feel free to open a new one if the problem persists.
